language: python
python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install --upgrade setuptools
  - pip install codecov
  - pip install -r requirements-dev.txt
  - python setup.py develop

script:
  make cov
after_success:
  codecov

env:
  matrix:
    - PYTHONASYNCIODEBUG=1
    - PYTHONASYNCIODEBUG=0


deploy:
  provider: pypi
  user: andrew.svetlov
  password:
    secure: "BKxLe+OLrJIatBuWQdkpjj0JVEBXOmD0q6/gLu8SVyR1trQ9moguEFkxCzZsRVWyD1oxb09AA3PX4wmZ7xoHuRyteyuOkkgo41Vbv9S0rUEXdSISv0VxbM6hO3vctYiozp1v56VcpWJbUIdmiL1feTyQEIJ4KwH3pASP6IOTVkw="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    python: 3.7
